# https://fly.io/docs/reference/configuration/

app = 'alriadb-tailscaled'
primary_region = '<your_region>'
swap_size_mb = 512

[build]

[deploy]
  strategy = 'immediate'

[env]
  # Tailscale configuration
  TS_HOSTNAME: <your_hostname>

  # DB configuration
  MYSQL_DATABASE: <your_database_name>
  MYSQL_CHARSET: utf8mb4
  MYSQL_COLLATION: utf8mb4_unicode_ci
  MYSQL_USER: mysql

[[mounts]]
  source = 'mariadb'
  destination = '/data/mariadb/alriadb-tailscaled'

[[vm]]
  memory = '<your_memory_size>'
  cpu_kind = '<your_cpu_kind>'
  cpus = <your_cpu_core_count>

# https://fly.io/calculator

